export const data = [
    {
      "time": "2/12/2016 11:35:57",
      "current_temp": "66.488",
      "target_temp": "50",
      "outside_temp": "77.7",
      "heater_val": "55",
      "humidity": "44",
      "outside_humiity": "62%",
      "pressure": "30.27",
      "weather": "Clear",
      "wind_speed": "4",
      "wind_degrees": "210",
      "precip_today": "0",
      "solar_radiation": "--",
      "heater_state": "FALSE",
      "auto_away": "-1",
      "local_epoch": "1455298557",
      "local_tz_short": "CST"
    },
    {
      "time": "2/12/2016 11:45:31",
      "current_temp": "66.524",
      "target_temp": "50",
      "outside_temp": "78.1",
      "heater_val": "55",
      "humidity": "44",
      "outside_humiity": "62%",
      "pressure": "30.27",
      "weather": "Clear",
      "wind_speed": "2.9",
      "wind_degrees": "175",
      "precip_today": "0",
      "solar_radiation": "--",
      "heater_state": "FALSE",
      "auto_away": "-1",
      "local_epoch": "1455299131",
      "local_tz_short": "CST"
    },
    {
      "time": "2/12/2016 11:54:21",
      "current_temp": "66.524",
      "target_temp": "50",
      "outside_temp": "78.4",
      "heater_val": "55",
      "humidity": "44",
      "outside_humiity": "61%",
      "pressure": "30.27",
      "weather": "Clear",
      "wind_speed": "0.9",
      "wind_degrees": "228",
      "precip_today": "0",
      "solar_radiation": "--",
      "heater_state": "FALSE",
      "auto_away": "-1",
      "local_epoch": "1455299661",
      "local_tz_short": "CST"
    },
    {
      "time": "2/12/2016 12:02:51",
      "current_temp": "66.524",
      "target_temp": "50",
      "outside_temp": "79.2",
      "heater_val": "55",
      "humidity": "44",
      "outside_humiity": "58%",
      "pressure": "30.25",
      "weather": "Partly Cloudy",
      "wind_speed": "2",
      "wind_degrees": "228",
      "precip_today": "0",
      "solar_radiation": "--",
      "heater_state": "FALSE",
      "auto_away": "-1",
      "local_epoch": "1455300170",
      "local_tz_short": "CST"
    },
    {
      "time": "2/12/2016 12:09:28",
      "current_temp": "66.524",
      "target_temp": "50",
      "outside_temp": "79.5",
      "heater_val": "55",
      "humidity": "44",
      "outside_humiity": "59%",
      "pressure": "30.25",
      "weather": "Partly Cloudy",
      "wind_speed": "2",
      "wind_degrees": "225",
      "precip_today": "0",
      "solar_radiation": "--",
      "heater_state": "FALSE",
      "auto_away": "-1",
      "local_epoch": "1455300567",
      "local_tz_short": "CST"
    },
    {
      "time": "2/12/2016 12:14:59",
      "current_temp": "66.524",
      "target_temp": "50",
      "outside_temp": "79.9",
      "heater_val": "55",
      "humidity": "44",
      "outside_humiity": "56%",
      "pressure": "30.25",
      "weather": "Partly Cloudy",
      "wind_speed": "2.9",
      "wind_degrees": "242",
      "precip_today": "0",
      "solar_radiation": "--",
      "heater_state": "FALSE",
      "auto_away": "-1",
      "local_epoch": "1455300898",
      "local_tz_short": "CST"
    },
    {
      "time": "2/12/2016 12:17:25",
      "current_temp": "66.524",
      "target_temp": "50",
      "outside_temp": "79.9",
      "heater_val": "55",
      "humidity": "44",
      "outside_humiity": "58%",
      "pressure": "30.25",
      "weather": "Partly Cloudy",
      "wind_speed": "2.9",
      "wind_degrees": "183",
      "precip_today": "0",
      "solar_radiation": "--",
      "heater_state": "FALSE",
      "auto_away": "-1",
      "local_epoch": "1455301044",
      "local_tz_short": "CST"
    },
    {
      "time": "2/12/2016 12:20:27",
      "current_temp": "66.524",
      "target_temp": "50",
      "outside_temp": "80.1",
      "heater_val": "55",
      "humidity": "44",
      "outside_humiity": "57%",
      "pressure": "30.25",
      "weather": "Partly Cloudy",
      "wind_speed": "2",
      "wind_degrees": "225",
      "precip_today": "0",
      "solar_radiation": "--",
      "heater_state": "FALSE",
      "auto_away": "-1",
      "local_epoch": "1455301227",
      "local_tz_short": "CST"
    },
    {
      "time": "2/12/2016 12:22:25",
      "current_temp": "66.524",
      "target_temp": "50",
      "outside_temp": "80.2",
      "heater_val": "55",
      "humidity": "44",
      "outside_humiity": "58%",
      "pressure": "30.25",
      "weather": "Partly Cloudy",
      "wind_speed": "2",
      "wind_degrees": "234",
      "precip_today": "0",
      "solar_radiation": "--",
      "heater_state": "FALSE",
      "auto_away": "-1",
      "local_epoch": "1455301344",
      "local_tz_short": "CST"
    },
    {
      "time": "2/12/2016 12:27:25",
      "current_temp": "66.524",
      "target_temp": "50",
      "outside_temp": "80.4",
      "heater_val": "55",
      "humidity": "44",
      "outside_humiity": "57%",
      "pressure": "30.25",
      "weather": "Partly Cloudy",
      "wind_speed": "4",
      "wind_degrees": "244",
      "precip_today": "0",
      "solar_radiation": "--",
      "heater_state": "FALSE",
      "auto_away": "-1",
      "local_epoch": "1455301645",
      "local_tz_short": "CST"
    },
    {
      "time": "2/12/2016 12:30:33",
      "current_temp": "66.524",
      "target_temp": "50",
      "outside_temp": "80.6",
      "heater_val": "55",
      "humidity": "44",
      "outside_humiity": "56%",
      "pressure": "30.25",
      "weather": "Partly Cloudy",
      "wind_speed": "2",
      "wind_degrees": "223",
      "precip_today": "0",
      "solar_radiation": "--",
      "heater_state": "FALSE",
      "auto_away": "-1",
      "local_epoch": "1455301833",
      "local_tz_short": "CST"
    },
    {
      "time": "2/12/2016 12:36:00",
      "current_temp": "66.524",
      "target_temp": "50",
      "outside_temp": "80.8",
      "heater_val": "55",
      "humidity": "44",
      "outside_humiity": "55%",
      "pressure": "30.25",
      "weather": "Partly Cloudy",
      "wind_speed": "4",
      "wind_degrees": "236",
      "precip_today": "0",
      "solar_radiation": "--",
      "heater_state": "FALSE",
      "auto_away": "-1",
      "local_epoch": "1455302025",
      "local_tz_short": "CST"
    },
    {
      "time": "2/12/2016 12:40:15",
      "current_temp": "66.524",
      "target_temp": "50",
      "outside_temp": "81",
      "heater_val": "55",
      "humidity": "44",
      "outside_humiity": "56%",
      "pressure": "30.25",
      "weather": "Partly Cloudy",
      "wind_speed": "2",
      "wind_degrees": "93",
      "precip_today": "0",
      "solar_radiation": "--",
      "heater_state": "FALSE",
      "auto_away": "-1",
      "local_epoch": "1455302414",
      "local_tz_short": "CST"
    },
    {
      "time": "2/12/2016 12:42:25",
      "current_temp": "66.524",
      "target_temp": "50",
      "outside_temp": "81.1",
      "heater_val": "55",
      "humidity": "44",
      "outside_humiity": "56%",
      "pressure": "30.25",
      "weather": "Partly Cloudy",
      "wind_speed": "0.9",
      "wind_degrees": "233",
      "precip_today": "0",
      "solar_radiation": "--",
      "heater_state": "FALSE",
      "auto_away": "-1",
      "local_epoch": "1455302544",
      "local_tz_short": "CST"
    },
    {
      "time": "2/12/2016 12:47:25",
      "current_temp": "66.524",
      "target_temp": "50",
      "outside_temp": "81.5",
      "heater_val": "55",
      "humidity": "44",
      "outside_humiity": "53%",
      "pressure": "30.25",
      "weather": "Partly Cloudy",
      "wind_speed": "2",
      "wind_degrees": "229",
      "precip_today": "0",
      "solar_radiation": "--",
      "heater_state": "FALSE",
      "auto_away": "-1",
      "local_epoch": "1455302844",
      "local_tz_short": "CST"
    },
    {
      "time": "2/12/2016 12:52:25",
      "current_temp": "66.524",
      "target_temp": "50",
      "outside_temp": "81.7",
      "heater_val": "55",
      "humidity": "46",
      "outside_humiity": "55%",
      "pressure": "30.25",
      "weather": "Partly Cloudy",
      "wind_speed": "0.9",
      "wind_degrees": "200",
      "precip_today": "0",
      "solar_radiation": "--",
      "heater_state": "FALSE",
      "auto_away": "-1",
      "local_epoch": "1455303144",
      "local_tz_short": "CST"
    },
    {
      "time": "2/12/2016 12:57:25",
      "current_temp": "66.524",
      "target_temp": "50",
      "outside_temp": "82.2",
      "heater_val": "55",
      "humidity": "46",
      "outside_humiity": "55%",
      "pressure": "30.23",
      "weather": "Partly Cloudy",
      "wind_speed": "0.9",
      "wind_degrees": "235",
      "precip_today": "0",
      "solar_radiation": "--",
      "heater_state": "FALSE",
      "auto_away": "-1",
      "local_epoch": "1455303444",
      "local_tz_short": "CST"
    },
    {
      "time": "2/12/2016 13:02:25",
      "current_temp": "66.524",
      "target_temp": "50",
      "outside_temp": "82.6",
      "heater_val": "55",
      "humidity": "46",
      "outside_humiity": "52%",
      "pressure": "30.23",
      "weather": "Partly Cloudy",
      "wind_speed": "0.9",
      "wind_degrees": "217",
      "precip_today": "0",
      "solar_radiation": "--",
      "heater_state": "FALSE",
      "auto_away": "-1",
      "local_epoch": "1455303744",
      "local_tz_short": "CST"
    },
    {
      "time": "2/12/2016 13:07:25",
      "current_temp": "66.524",
      "target_temp": "50",
      "outside_temp": "82.8",
      "heater_val": "55",
      "humidity": "46",
      "outside_humiity": "51%",
      "pressure": "30.23",
      "weather": "Partly Cloudy",
      "wind_speed": "2",
      "wind_degrees": "247",
      "precip_today": "0",
      "solar_radiation": "--",
      "heater_state": "FALSE",
      "auto_away": "-1",
      "local_epoch": "1455304044",
      "local_tz_short": "CST"
    },
    {
      "time": "2/12/2016 13:12:25",
      "current_temp": "66.524",
      "target_temp": "50",
      "outside_temp": "82.8",
      "heater_val": "55",
      "humidity": "46",
      "outside_humiity": "51%",
      "pressure": "30.23",
      "weather": "Partly Cloudy",
      "wind_speed": "0.9",
      "wind_degrees": "255",
      "precip_today": "0",
      "solar_radiation": "--",
      "heater_state": "FALSE",
      "auto_away": "-1",
      "local_epoch": "1455304344",
      "local_tz_short": "CST"
    },
    {
      "time": "2/12/2016 13:22:24",
      "current_temp": "67.55",
      "target_temp": "50",
      "outside_temp": "82.6",
      "heater_val": "55",
      "humidity": "46",
      "outside_humiity": "50%",
      "pressure": "30.23",
      "weather": "Partly Cloudy",
      "wind_speed": "2",
      "wind_degrees": "211",
      "precip_today": "0",
      "solar_radiation": "--",
      "heater_state": "FALSE",
      "auto_away": "-1",
      "local_epoch": "1455304944",
      "local_tz_short": "CST"
    },
    {
      "time": "2/12/2016 13:27:25",
      "current_temp": "67.55",
      "target_temp": "50",
      "outside_temp": "82.6",
      "heater_val": "55",
      "humidity": "46",
      "outside_humiity": "52%",
      "pressure": "30.23",
      "weather": "Partly Cloudy",
      "wind_speed": "2",
      "wind_degrees": "252",
      "precip_today": "0",
      "solar_radiation": "--",
      "heater_state": "FALSE",
      "auto_away": "-1",
      "local_epoch": "1455305245",
      "local_tz_short": "CST"
    },
    {
      "time": "2/12/2016 13:32:25",
      "current_temp": "67.55",
      "target_temp": "50",
      "outside_temp": "82.8",
      "heater_val": "55",
      "humidity": "46",
      "outside_humiity": "52%",
      "pressure": "30.23",
      "weather": "Partly Cloudy",
      "wind_speed": "0",
      "wind_degrees": "274",
      "precip_today": "0",
      "solar_radiation": "--",
      "heater_state": "FALSE",
      "auto_away": "-1",
      "local_epoch": "1455305544",
      "local_tz_short": "CST"
    },
    {
      "time": "2/12/2016 13:37:25",
      "current_temp": "67.55",
      "target_temp": "50",
      "outside_temp": "83.1",
      "heater_val": "55",
      "humidity": "46",
      "outside_humiity": "50%",
      "pressure": "30.23",
      "weather": "Partly Cloudy",
      "wind_speed": "2",
      "wind_degrees": "228",
      "precip_today": "0",
      "solar_radiation": "--",
      "heater_state": "FALSE",
      "auto_away": "-1",
      "local_epoch": "1455305844",
      "local_tz_short": "CST"
    },
    {
      "time": "2/12/2016 13:42:25",
      "current_temp": "67.55",
      "target_temp": "50",
      "outside_temp": "83.1",
      "heater_val": "55",
      "humidity": "46",
      "outside_humiity": "50%",
      "pressure": "30.23",
      "weather": "Partly Cloudy",
      "wind_speed": "4",
      "wind_degrees": "209",
      "precip_today": "0",
      "solar_radiation": "--",
      "heater_state": "FALSE",
      "auto_away": "-1",
      "local_epoch": "1455306144",
      "local_tz_short": "CST"
    },
    {
      "time": "2/12/2016 13:47:25",
      "current_temp": "67.55",
      "target_temp": "50",
      "outside_temp": "83.1",
      "heater_val": "55",
      "humidity": "46",
      "outside_humiity": "51%",
      "pressure": "30.23",
      "weather": "Partly Cloudy",
      "wind_speed": "2",
      "wind_degrees": "221",
      "precip_today": "0",
      "solar_radiation": "--",
      "heater_state": "FALSE",
      "auto_away": "-1",
      "local_epoch": "1455306444",
      "local_tz_short": "CST"
    }
  ]